### ISSUE TITLE
colophon / license

### ISSUE THREAD

**Issue by Boruch-Baum** [thblt/pgp-words#1]
Please consider adding comment lines in the executable to identify the project url (I guess this github repository), the author / mantainer copyright and contact info, the license (or say public domain), and some sort of version / date.

**Comment by thblt** [comment]
Sure, why not. Is there a standard format for that, or something that'd be useful to you?

**Comment by Boruch-Baum** [comment]
On 2020-02-18 07:45, Thibault Polge wrote:
>    Sure, why not. Is there a standard format for that, or something that'd
>    be useful to you?

Take a look at the source code of several projects that you respect, and
see how they do it; there's no absolute mandatory style. The GNU project
has its own standard; BSD, Canonical and Red Hat probably each have
theirs.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
